### PR TITLE
Add support for Krastorio loaders

### PR DESCRIPTION
**Pull request by ExE-Boss**
This adds basic compatibility for **Krastorio’s** loaders and also fixes the **Fast** and **Express** inserter recipes when **K2+SE** is present.

I chose not to add **Basic Loaders**, as **Krastorio** loaders are unlocked from the same research as the belt and only need electricity to operate, so it doesn’t make as much sense to add those as it does with **AAI Loaders**, which use fluids to operate.

## Related issues
- https://github.com/modded-factorio/bobsmods/pull/154
- https://github.com/modded-factorio/bobsmods/pull/164
- https://github.com/modded-factorio/bobsmods/issues/153
- https://github.com/raiguard/Krastorio2/issues/404

### CODE REVIEW

**Comment by KiwiHawk** [comment]
Krastorio2 already has purple and green tier loaders (as well as matching belts, undergrounds, and splitters).

image

image

Rather than creating additional new entities, I think it would be best to use the existing ones:
- Hide these entities and recipes
  - Turbo Transport Belt
  - Turbo Underground Belt
  - Turbo Splitter
  - Ultimate Transport Belt
  - Ultimate Underground Belt
  - Ultimate Splitter
- Update the underground distance on the following:
  - Advanced Underground Belt: Max underground distance of Advanced Underground Belt / Turbo Underground Belt
  - Superior Underground Belt: Max underground distance of Superior Underground Belt / Ultimate Underground Belt
- Update the subgroup for the following so they line up with Bob's:
  - Advanced Transport Belt
  - Superior Transport Belt
  - Advanced Underground Belt
  - Superior Underground Belt
  - Advanced Splitter
  - Superior Splitter
  - Loader
  - Fast Loader
  - Express Loader
  - Advanced Loader
  - Superior Loader
- Hide the following Bob's techs. Update anything that has it as a prerequisite to use the Krastorio 2 version:
  - Logistics 4
  - Logistics 5

**Comment by Qatavin** [comment]
We could go with either the Bob's two top tiers of belts or the K2 belts, but I think sticking with the Bob's belts would be best. That would be more convenient for the setting that allows you to change the speeds of the belts, and it would keep the colors consistent with the inserters and everything else, since K2 belts go green and then purple instead of purple and then green.

It should still not be necessary to generate new loaders, though. It would work just as well to repurpose the current K2 ones by swapping their graphics and adjusting them so their speeds match whatever the Bob's belts have (since their speed is adjustable).

**Comment by KiwiHawk** [comment]
Yes, that also works.

**Comment by Qatavin** [comment]
All of this has been taken care of by my new B+SE+K2 mod as well.

**Pull request closed without merging**
